
# application.yml 같은 yml 파일은 띄어쓰기 2칸으로 계층
# 스프링 부트는 datasource 설정이 없으면, 기본적을 메모리 DB를 사용하고, driver-class도 현재 등록된
# 라이브러를 보고 찾아준다. 추가로 ddl-auto 도 create-drop 모드로 동작한다. 따라서 데이터소스나,
#JPA 관련된 별도의 추가 설정을 하지 않아도 된다
spring:
 # datasource:
    # DB 모드 방식  -url: jdbc:h2:tcp://localhost/~/jpashop
    # 메모리 DB 모드로 동작 - H2 데이터베이스 종료해도 test 성공
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
       # create-create: 기존테이블 삭제 후 다시 생성 (DROP + CREATE)
       # create-drop: create와 같으나 종료시점에 테이블 DROP -  메모리 완전히 초기화 시키기
#    properties:
#      hibernate:
    # show_sql: true : System.out으로 하이버네이트 실행 SQL을 남긴다
        # format_sql :logger를 통해 하이버네이트 실행 SQL을 남긴다.
#        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace